add getSaleRequire function
evolutionlandorg/bancor-contracts pull request #11
Opened 2018-09-30 10:32 UTC by hammeWang

close #9

2018-09-30 10:34 UTC, hammeWang commented
this may not precise.

2018-10-02 01:37 UTC, hackfisher requested changes

2018-10-02 01:37 UTC, HackFisher commented on solidity/contracts/converter/BancorConverter.sol
> +    function getSaleRequire(IERC20Token _connectorToken, uint256 _sellAmount)
What is the difference between ```getSaleRequire``` and ```getSaleReturn```? It seems that they have the same input and return the same value. 

Why not input the eth as parameter and return the required minimum amount of smart token need to give?

2018-10-08 05:30 UTC, hammeWang commented
NOTE: getSaleRequire function is not extremely precise. Use carefully.

2018-10-08 06:17 UTC, merged